{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "now limit:  0\n",
      "rm all npy\n",
      "['__class__',\n",
      " '__contains__',\n",
      " '__delattr__',\n",
      " '__dict__',\n",
      " '__dir__',\n",
      " '__doc__',\n",
      " '__eq__',\n",
      " '__format__',\n",
      " '__ge__',\n",
      " '__getattribute__',\n",
      " '__gt__',\n",
      " '__hash__',\n",
      " '__init__',\n",
      " '__init_subclass__',\n",
      " '__le__',\n",
      " '__lt__',\n",
      " '__module__',\n",
      " '__ne__',\n",
      " '__new__',\n",
      " '__reduce__',\n",
      " '__reduce_ex__',\n",
      " '__repr__',\n",
      " '__setattr__',\n",
      " '__sizeof__',\n",
      " '__str__',\n",
      " '__subclasshook__',\n",
      " '__weakref__',\n",
      " '_get_args',\n",
      " '_get_kwargs',\n",
      " 'alpha',\n",
      " 'enable_overwrite',\n",
      " 'f0_estimating_method',\n",
      " 'frame_period',\n",
      " 'input_directory',\n",
      " 'order',\n",
      " 'output_directory',\n",
      " 'pad_second',\n",
      " 'sample_rate',\n",
      " 'top_db']\n",
      "100%|███████████████████████████████████████████| 25/25 [00:03<00:00,  2.99it/s]\n",
      "/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/normalization/batch_normalization.py:67: UserWarning: A batch with no more than one sample has been given to F.batch_normalization. F.batch_normalization will always output a zero tensor for such batches. This could be caused by incorrect configuration in your code (such as running evaluation while chainer.config.train=True), but could also happen in the last batch of training if non-repeating iterator is used.\n",
      "  UserWarning)\n",
      "predictor/loss\n",
      "Exception in main training loop: \n",
      "Invalid operation is performed in: Concat (Forward)\n",
      "\n",
      "Expect: in_types[0].shape[2] == in_types[1].shape[2]\n",
      "Actual: 6 != 7\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 319, in run\n",
      "    entry.extension(self)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 157, in __call__\n",
      "    result = self.evaluate()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 211, in evaluate\n",
      "    eval_func(**in_arrays)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/updater/sr_updater.py\", line 61, in forward\n",
      "    output = self.predictor(input)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 101, in __call__\n",
      "    return self.decoder(self.encoder(x))\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 85, in __call__\n",
      "    h = F.concat([h, hs[-i - 1]])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 105, in concat\n",
      "    y, = Concat(axis).apply(xs)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 243, in apply\n",
      "    self._check_data_type_forward(in_data)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 328, in _check_data_type_forward\n",
      "    self.check_type_forward(in_type)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 41, in check_type_forward\n",
      "    type_check.expect(in_types[0].shape[d] == in_types[i].shape[d])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 524, in expect\n",
      "    expr.expect()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 482, in expect\n",
      "    '{0} {1} {2}'.format(left, self.inv, right))\n",
      "Will finalize trainer extensions and updater before reraising the exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"train_sr.py\", line 85, in <module>\n",
      "    trainer.run()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 330, in run\n",
      "    six.reraise(*sys.exc_info())\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/six.py\", line 693, in reraise\n",
      "    raise value\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 319, in run\n",
      "    entry.extension(self)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 157, in __call__\n",
      "    result = self.evaluate()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 211, in evaluate\n",
      "    eval_func(**in_arrays)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/updater/sr_updater.py\", line 61, in forward\n",
      "    output = self.predictor(input)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 101, in __call__\n",
      "    return self.decoder(self.encoder(x))\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 85, in __call__\n",
      "    h = F.concat([h, hs[-i - 1]])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 105, in concat\n",
      "    y, = Concat(axis).apply(xs)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 243, in apply\n",
      "    self._check_data_type_forward(in_data)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 328, in _check_data_type_forward\n",
      "    self.check_type_forward(in_type)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 41, in check_type_forward\n",
      "    type_check.expect(in_types[0].shape[d] == in_types[i].shape[d])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 524, in expect\n",
      "    expr.expect()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 482, in expect\n",
      "    '{0} {1} {2}'.format(left, self.inv, right))\n",
      "chainer.utils.type_check.InvalidType: \n",
      "Invalid operation is performed in: Concat (Forward)\n",
      "\n",
      "Expect: in_types[0].shape[2] == in_types[1].shape[2]\n",
      "Actual: 6 != 7\n",
      "now limit:  0.1\n",
      "rm all npy\n",
      "['__class__',\n",
      " '__contains__',\n",
      " '__delattr__',\n",
      " '__dict__',\n",
      " '__dir__',\n",
      " '__doc__',\n",
      " '__eq__',\n",
      " '__format__',\n",
      " '__ge__',\n",
      " '__getattribute__',\n",
      " '__gt__',\n",
      " '__hash__',\n",
      " '__init__',\n",
      " '__init_subclass__',\n",
      " '__le__',\n",
      " '__lt__',\n",
      " '__module__',\n",
      " '__ne__',\n",
      " '__new__',\n",
      " '__reduce__',\n",
      " '__reduce_ex__',\n",
      " '__repr__',\n",
      " '__setattr__',\n",
      " '__sizeof__',\n",
      " '__str__',\n",
      " '__subclasshook__',\n",
      " '__weakref__',\n",
      " '_get_args',\n",
      " '_get_kwargs',\n",
      " 'alpha',\n",
      " 'enable_overwrite',\n",
      " 'f0_estimating_method',\n",
      " 'frame_period',\n",
      " 'input_directory',\n",
      " 'order',\n",
      " 'output_directory',\n",
      " 'pad_second',\n",
      " 'sample_rate',\n",
      " 'top_db']\n",
      "100%|███████████████████████████████████████████| 25/25 [00:03<00:00,  7.17it/s]\n",
      "/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/normalization/batch_normalization.py:67: UserWarning: A batch with no more than one sample has been given to F.batch_normalization. F.batch_normalization will always output a zero tensor for such batches. This could be caused by incorrect configuration in your code (such as running evaluation while chainer.config.train=True), but could also happen in the last batch of training if non-repeating iterator is used.\n",
      "  UserWarning)\n",
      "predictor/loss\n",
      "Exception in main training loop: \n",
      "Invalid operation is performed in: Concat (Forward)\n",
      "\n",
      "Expect: in_types[0].shape[2] == in_types[1].shape[2]\n",
      "Actual: 6 != 7\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 319, in run\n",
      "    entry.extension(self)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 157, in __call__\n",
      "    result = self.evaluate()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 211, in evaluate\n",
      "    eval_func(**in_arrays)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/updater/sr_updater.py\", line 61, in forward\n",
      "    output = self.predictor(input)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 101, in __call__\n",
      "    return self.decoder(self.encoder(x))\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 85, in __call__\n",
      "    h = F.concat([h, hs[-i - 1]])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 105, in concat\n",
      "    y, = Concat(axis).apply(xs)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 243, in apply\n",
      "    self._check_data_type_forward(in_data)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 328, in _check_data_type_forward\n",
      "    self.check_type_forward(in_type)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 41, in check_type_forward\n",
      "    type_check.expect(in_types[0].shape[d] == in_types[i].shape[d])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 524, in expect\n",
      "    expr.expect()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 482, in expect\n",
      "    '{0} {1} {2}'.format(left, self.inv, right))\n",
      "Will finalize trainer extensions and updater before reraising the exception.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"train_sr.py\", line 85, in <module>\n",
      "    trainer.run()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 330, in run\n",
      "    six.reraise(*sys.exc_info())\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/six.py\", line 693, in reraise\n",
      "    raise value\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 319, in run\n",
      "    entry.extension(self)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 157, in __call__\n",
      "    result = self.evaluate()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 211, in evaluate\n",
      "    eval_func(**in_arrays)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/updater/sr_updater.py\", line 61, in forward\n",
      "    output = self.predictor(input)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 101, in __call__\n",
      "    return self.decoder(self.encoder(x))\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 85, in __call__\n",
      "    h = F.concat([h, hs[-i - 1]])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 105, in concat\n",
      "    y, = Concat(axis).apply(xs)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 243, in apply\n",
      "    self._check_data_type_forward(in_data)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 328, in _check_data_type_forward\n",
      "    self.check_type_forward(in_type)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 41, in check_type_forward\n",
      "    type_check.expect(in_types[0].shape[d] == in_types[i].shape[d])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 524, in expect\n",
      "    expr.expect()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 482, in expect\n",
      "    '{0} {1} {2}'.format(left, self.inv, right))\n",
      "chainer.utils.type_check.InvalidType: \n",
      "Invalid operation is performed in: Concat (Forward)\n",
      "\n",
      "Expect: in_types[0].shape[2] == in_types[1].shape[2]\n",
      "Actual: 6 != 7\n",
      "now limit:  0.2\n",
      "rm all npy\n",
      "['__class__',\n",
      " '__contains__',\n",
      " '__delattr__',\n",
      " '__dict__',\n",
      " '__dir__',\n",
      " '__doc__',\n",
      " '__eq__',\n",
      " '__format__',\n",
      " '__ge__',\n",
      " '__getattribute__',\n",
      " '__gt__',\n",
      " '__hash__',\n",
      " '__init__',\n",
      " '__init_subclass__',\n",
      " '__le__',\n",
      " '__lt__',\n",
      " '__module__',\n",
      " '__ne__',\n",
      " '__new__',\n",
      " '__reduce__',\n",
      " '__reduce_ex__',\n",
      " '__repr__',\n",
      " '__setattr__',\n",
      " '__sizeof__',\n",
      " '__str__',\n",
      " '__subclasshook__',\n",
      " '__weakref__',\n",
      " '_get_args',\n",
      " '_get_kwargs',\n",
      " 'alpha',\n",
      " 'enable_overwrite',\n",
      " 'f0_estimating_method',\n",
      " 'frame_period',\n",
      " 'input_directory',\n",
      " 'order',\n",
      " 'output_directory',\n",
      " 'pad_second',\n",
      " 'sample_rate',\n",
      " 'top_db']\n",
      "100%|███████████████████████████████████████████| 25/25 [00:03<00:00,  7.26it/s]\n",
      "/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/normalization/batch_normalization.py:67: UserWarning: A batch with no more than one sample has been given to F.batch_normalization. F.batch_normalization will always output a zero tensor for such batches. This could be caused by incorrect configuration in your code (such as running evaluation while chainer.config.train=True), but could also happen in the last batch of training if non-repeating iterator is used.\n",
      "  UserWarning)\n",
      "predictor/loss\n",
      "Exception in main training loop: \n",
      "Invalid operation is performed in: Concat (Forward)\n",
      "\n",
      "Expect: in_types[0].shape[2] == in_types[1].shape[2]\n",
      "Actual: 6 != 7\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 319, in run\n",
      "    entry.extension(self)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 157, in __call__\n",
      "    result = self.evaluate()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 211, in evaluate\n",
      "    eval_func(**in_arrays)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/updater/sr_updater.py\", line 61, in forward\n",
      "    output = self.predictor(input)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 101, in __call__\n",
      "    return self.decoder(self.encoder(x))\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 85, in __call__\n",
      "    h = F.concat([h, hs[-i - 1]])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 105, in concat\n",
      "    y, = Concat(axis).apply(xs)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 243, in apply\n",
      "    self._check_data_type_forward(in_data)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 328, in _check_data_type_forward\n",
      "    self.check_type_forward(in_type)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 41, in check_type_forward\n",
      "    type_check.expect(in_types[0].shape[d] == in_types[i].shape[d])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 524, in expect\n",
      "    expr.expect()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 482, in expect\n",
      "    '{0} {1} {2}'.format(left, self.inv, right))\n",
      "Will finalize trainer extensions and updater before reraising the exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"train_sr.py\", line 85, in <module>\n",
      "    trainer.run()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 330, in run\n",
      "    six.reraise(*sys.exc_info())\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/six.py\", line 693, in reraise\n",
      "    raise value\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 319, in run\n",
      "    entry.extension(self)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 157, in __call__\n",
      "    result = self.evaluate()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 211, in evaluate\n",
      "    eval_func(**in_arrays)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/updater/sr_updater.py\", line 61, in forward\n",
      "    output = self.predictor(input)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 101, in __call__\n",
      "    return self.decoder(self.encoder(x))\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 85, in __call__\n",
      "    h = F.concat([h, hs[-i - 1]])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 105, in concat\n",
      "    y, = Concat(axis).apply(xs)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 243, in apply\n",
      "    self._check_data_type_forward(in_data)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 328, in _check_data_type_forward\n",
      "    self.check_type_forward(in_type)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 41, in check_type_forward\n",
      "    type_check.expect(in_types[0].shape[d] == in_types[i].shape[d])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 524, in expect\n",
      "    expr.expect()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 482, in expect\n",
      "    '{0} {1} {2}'.format(left, self.inv, right))\n",
      "chainer.utils.type_check.InvalidType: \n",
      "Invalid operation is performed in: Concat (Forward)\n",
      "\n",
      "Expect: in_types[0].shape[2] == in_types[1].shape[2]\n",
      "Actual: 6 != 7\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "now limit:  0.30000000000000004\n",
      "rm all npy\n",
      "['__class__',\n",
      " '__contains__',\n",
      " '__delattr__',\n",
      " '__dict__',\n",
      " '__dir__',\n",
      " '__doc__',\n",
      " '__eq__',\n",
      " '__format__',\n",
      " '__ge__',\n",
      " '__getattribute__',\n",
      " '__gt__',\n",
      " '__hash__',\n",
      " '__init__',\n",
      " '__init_subclass__',\n",
      " '__le__',\n",
      " '__lt__',\n",
      " '__module__',\n",
      " '__ne__',\n",
      " '__new__',\n",
      " '__reduce__',\n",
      " '__reduce_ex__',\n",
      " '__repr__',\n",
      " '__setattr__',\n",
      " '__sizeof__',\n",
      " '__str__',\n",
      " '__subclasshook__',\n",
      " '__weakref__',\n",
      " '_get_args',\n",
      " '_get_kwargs',\n",
      " 'alpha',\n",
      " 'enable_overwrite',\n",
      " 'f0_estimating_method',\n",
      " 'frame_period',\n",
      " 'input_directory',\n",
      " 'order',\n",
      " 'output_directory',\n",
      " 'pad_second',\n",
      " 'sample_rate',\n",
      " 'top_db']\n",
      "100%|███████████████████████████████████████████| 25/25 [00:03<00:00,  7.32it/s]\n",
      "/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/normalization/batch_normalization.py:67: UserWarning: A batch with no more than one sample has been given to F.batch_normalization. F.batch_normalization will always output a zero tensor for such batches. This could be caused by incorrect configuration in your code (such as running evaluation while chainer.config.train=True), but could also happen in the last batch of training if non-repeating iterator is used.\n",
      "  UserWarning)\n",
      "predictor/loss\n",
      "Exception in main training loop: \n",
      "Invalid operation is performed in: Concat (Forward)\n",
      "\n",
      "Expect: in_types[0].shape[2] == in_types[1].shape[2]\n",
      "Actual: 6 != 7\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 319, in run\n",
      "    entry.extension(self)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 157, in __call__\n",
      "    result = self.evaluate()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 211, in evaluate\n",
      "    eval_func(**in_arrays)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/updater/sr_updater.py\", line 61, in forward\n",
      "    output = self.predictor(input)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 101, in __call__\n",
      "    return self.decoder(self.encoder(x))\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 85, in __call__\n",
      "    h = F.concat([h, hs[-i - 1]])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 105, in concat\n",
      "    y, = Concat(axis).apply(xs)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 243, in apply\n",
      "    self._check_data_type_forward(in_data)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 328, in _check_data_type_forward\n",
      "    self.check_type_forward(in_type)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 41, in check_type_forward\n",
      "    type_check.expect(in_types[0].shape[d] == in_types[i].shape[d])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 524, in expect\n",
      "    expr.expect()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 482, in expect\n",
      "    '{0} {1} {2}'.format(left, self.inv, right))\n",
      "Will finalize trainer extensions and updater before reraising the exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"train_sr.py\", line 85, in <module>\n",
      "    trainer.run()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 330, in run\n",
      "    six.reraise(*sys.exc_info())\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/six.py\", line 693, in reraise\n",
      "    raise value\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 319, in run\n",
      "    entry.extension(self)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 157, in __call__\n",
      "    result = self.evaluate()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 211, in evaluate\n",
      "    eval_func(**in_arrays)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/updater/sr_updater.py\", line 61, in forward\n",
      "    output = self.predictor(input)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 101, in __call__\n",
      "    return self.decoder(self.encoder(x))\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 85, in __call__\n",
      "    h = F.concat([h, hs[-i - 1]])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 105, in concat\n",
      "    y, = Concat(axis).apply(xs)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 243, in apply\n",
      "    self._check_data_type_forward(in_data)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 328, in _check_data_type_forward\n",
      "    self.check_type_forward(in_type)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 41, in check_type_forward\n",
      "    type_check.expect(in_types[0].shape[d] == in_types[i].shape[d])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 524, in expect\n",
      "    expr.expect()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 482, in expect\n",
      "    '{0} {1} {2}'.format(left, self.inv, right))\n",
      "chainer.utils.type_check.InvalidType: \n",
      "Invalid operation is performed in: Concat (Forward)\n",
      "\n",
      "Expect: in_types[0].shape[2] == in_types[1].shape[2]\n",
      "Actual: 6 != 7\n",
      "now limit:  0.4\n",
      "rm all npy\n",
      "['__class__',\n",
      " '__contains__',\n",
      " '__delattr__',\n",
      " '__dict__',\n",
      " '__dir__',\n",
      " '__doc__',\n",
      " '__eq__',\n",
      " '__format__',\n",
      " '__ge__',\n",
      " '__getattribute__',\n",
      " '__gt__',\n",
      " '__hash__',\n",
      " '__init__',\n",
      " '__init_subclass__',\n",
      " '__le__',\n",
      " '__lt__',\n",
      " '__module__',\n",
      " '__ne__',\n",
      " '__new__',\n",
      " '__reduce__',\n",
      " '__reduce_ex__',\n",
      " '__repr__',\n",
      " '__setattr__',\n",
      " '__sizeof__',\n",
      " '__str__',\n",
      " '__subclasshook__',\n",
      " '__weakref__',\n",
      " '_get_args',\n",
      " '_get_kwargs',\n",
      " 'alpha',\n",
      " 'enable_overwrite',\n",
      " 'f0_estimating_method',\n",
      " 'frame_period',\n",
      " 'input_directory',\n",
      " 'order',\n",
      " 'output_directory',\n",
      " 'pad_second',\n",
      " 'sample_rate',\n",
      " 'top_db']\n",
      "100%|███████████████████████████████████████████| 25/25 [00:03<00:00,  7.36it/s]\n",
      "/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/normalization/batch_normalization.py:67: UserWarning: A batch with no more than one sample has been given to F.batch_normalization. F.batch_normalization will always output a zero tensor for such batches. This could be caused by incorrect configuration in your code (such as running evaluation while chainer.config.train=True), but could also happen in the last batch of training if non-repeating iterator is used.\n",
      "  UserWarning)\n",
      "predictor/loss\n",
      "Exception in main training loop: \n",
      "Invalid operation is performed in: Concat (Forward)\n",
      "\n",
      "Expect: in_types[0].shape[2] == in_types[1].shape[2]\n",
      "Actual: 6 != 7\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 319, in run\n",
      "    entry.extension(self)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 157, in __call__\n",
      "    result = self.evaluate()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 211, in evaluate\n",
      "    eval_func(**in_arrays)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/updater/sr_updater.py\", line 61, in forward\n",
      "    output = self.predictor(input)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 101, in __call__\n",
      "    return self.decoder(self.encoder(x))\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 85, in __call__\n",
      "    h = F.concat([h, hs[-i - 1]])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 105, in concat\n",
      "    y, = Concat(axis).apply(xs)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 243, in apply\n",
      "    self._check_data_type_forward(in_data)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 328, in _check_data_type_forward\n",
      "    self.check_type_forward(in_type)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 41, in check_type_forward\n",
      "    type_check.expect(in_types[0].shape[d] == in_types[i].shape[d])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 524, in expect\n",
      "    expr.expect()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 482, in expect\n",
      "    '{0} {1} {2}'.format(left, self.inv, right))\n",
      "Will finalize trainer extensions and updater before reraising the exception.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"train_sr.py\", line 85, in <module>\n",
      "    trainer.run()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 330, in run\n",
      "    six.reraise(*sys.exc_info())\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/six.py\", line 693, in reraise\n",
      "    raise value\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 319, in run\n",
      "    entry.extension(self)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 157, in __call__\n",
      "    result = self.evaluate()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 211, in evaluate\n",
      "    eval_func(**in_arrays)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/updater/sr_updater.py\", line 61, in forward\n",
      "    output = self.predictor(input)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 101, in __call__\n",
      "    return self.decoder(self.encoder(x))\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 85, in __call__\n",
      "    h = F.concat([h, hs[-i - 1]])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 105, in concat\n",
      "    y, = Concat(axis).apply(xs)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 243, in apply\n",
      "    self._check_data_type_forward(in_data)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 328, in _check_data_type_forward\n",
      "    self.check_type_forward(in_type)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 41, in check_type_forward\n",
      "    type_check.expect(in_types[0].shape[d] == in_types[i].shape[d])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 524, in expect\n",
      "    expr.expect()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 482, in expect\n",
      "    '{0} {1} {2}'.format(left, self.inv, right))\n",
      "chainer.utils.type_check.InvalidType: \n",
      "Invalid operation is performed in: Concat (Forward)\n",
      "\n",
      "Expect: in_types[0].shape[2] == in_types[1].shape[2]\n",
      "Actual: 6 != 7\n",
      "now limit:  0.5\n",
      "rm all npy\n",
      "['__class__',\n",
      " '__contains__',\n",
      " '__delattr__',\n",
      " '__dict__',\n",
      " '__dir__',\n",
      " '__doc__',\n",
      " '__eq__',\n",
      " '__format__',\n",
      " '__ge__',\n",
      " '__getattribute__',\n",
      " '__gt__',\n",
      " '__hash__',\n",
      " '__init__',\n",
      " '__init_subclass__',\n",
      " '__le__',\n",
      " '__lt__',\n",
      " '__module__',\n",
      " '__ne__',\n",
      " '__new__',\n",
      " '__reduce__',\n",
      " '__reduce_ex__',\n",
      " '__repr__',\n",
      " '__setattr__',\n",
      " '__sizeof__',\n",
      " '__str__',\n",
      " '__subclasshook__',\n",
      " '__weakref__',\n",
      " '_get_args',\n",
      " '_get_kwargs',\n",
      " 'alpha',\n",
      " 'enable_overwrite',\n",
      " 'f0_estimating_method',\n",
      " 'frame_period',\n",
      " 'input_directory',\n",
      " 'order',\n",
      " 'output_directory',\n",
      " 'pad_second',\n",
      " 'sample_rate',\n",
      " 'top_db']\n",
      "100%|███████████████████████████████████████████| 25/25 [00:03<00:00,  7.42it/s]\n",
      "/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/normalization/batch_normalization.py:67: UserWarning: A batch with no more than one sample has been given to F.batch_normalization. F.batch_normalization will always output a zero tensor for such batches. This could be caused by incorrect configuration in your code (such as running evaluation while chainer.config.train=True), but could also happen in the last batch of training if non-repeating iterator is used.\n",
      "  UserWarning)\n",
      "predictor/loss\n",
      "Exception in main training loop: \n",
      "Invalid operation is performed in: Concat (Forward)\n",
      "\n",
      "Expect: in_types[0].shape[2] == in_types[1].shape[2]\n",
      "Actual: 6 != 7\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 319, in run\n",
      "    entry.extension(self)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 157, in __call__\n",
      "    result = self.evaluate()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 211, in evaluate\n",
      "    eval_func(**in_arrays)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/updater/sr_updater.py\", line 61, in forward\n",
      "    output = self.predictor(input)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 101, in __call__\n",
      "    return self.decoder(self.encoder(x))\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 85, in __call__\n",
      "    h = F.concat([h, hs[-i - 1]])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 105, in concat\n",
      "    y, = Concat(axis).apply(xs)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 243, in apply\n",
      "    self._check_data_type_forward(in_data)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 328, in _check_data_type_forward\n",
      "    self.check_type_forward(in_type)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 41, in check_type_forward\n",
      "    type_check.expect(in_types[0].shape[d] == in_types[i].shape[d])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 524, in expect\n",
      "    expr.expect()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 482, in expect\n",
      "    '{0} {1} {2}'.format(left, self.inv, right))\n",
      "Will finalize trainer extensions and updater before reraising the exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"train_sr.py\", line 85, in <module>\n",
      "    trainer.run()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 330, in run\n",
      "    six.reraise(*sys.exc_info())\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/six.py\", line 693, in reraise\n",
      "    raise value\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 319, in run\n",
      "    entry.extension(self)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 157, in __call__\n",
      "    result = self.evaluate()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 211, in evaluate\n",
      "    eval_func(**in_arrays)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/updater/sr_updater.py\", line 61, in forward\n",
      "    output = self.predictor(input)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 101, in __call__\n",
      "    return self.decoder(self.encoder(x))\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 85, in __call__\n",
      "    h = F.concat([h, hs[-i - 1]])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 105, in concat\n",
      "    y, = Concat(axis).apply(xs)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 243, in apply\n",
      "    self._check_data_type_forward(in_data)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 328, in _check_data_type_forward\n",
      "    self.check_type_forward(in_type)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 41, in check_type_forward\n",
      "    type_check.expect(in_types[0].shape[d] == in_types[i].shape[d])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 524, in expect\n",
      "    expr.expect()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 482, in expect\n",
      "    '{0} {1} {2}'.format(left, self.inv, right))\n",
      "chainer.utils.type_check.InvalidType: \n",
      "Invalid operation is performed in: Concat (Forward)\n",
      "\n",
      "Expect: in_types[0].shape[2] == in_types[1].shape[2]\n",
      "Actual: 6 != 7\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "now limit:  0.6\n",
      "rm all npy\n",
      "['__class__',\n",
      " '__contains__',\n",
      " '__delattr__',\n",
      " '__dict__',\n",
      " '__dir__',\n",
      " '__doc__',\n",
      " '__eq__',\n",
      " '__format__',\n",
      " '__ge__',\n",
      " '__getattribute__',\n",
      " '__gt__',\n",
      " '__hash__',\n",
      " '__init__',\n",
      " '__init_subclass__',\n",
      " '__le__',\n",
      " '__lt__',\n",
      " '__module__',\n",
      " '__ne__',\n",
      " '__new__',\n",
      " '__reduce__',\n",
      " '__reduce_ex__',\n",
      " '__repr__',\n",
      " '__setattr__',\n",
      " '__sizeof__',\n",
      " '__str__',\n",
      " '__subclasshook__',\n",
      " '__weakref__',\n",
      " '_get_args',\n",
      " '_get_kwargs',\n",
      " 'alpha',\n",
      " 'enable_overwrite',\n",
      " 'f0_estimating_method',\n",
      " 'frame_period',\n",
      " 'input_directory',\n",
      " 'order',\n",
      " 'output_directory',\n",
      " 'pad_second',\n",
      " 'sample_rate',\n",
      " 'top_db']\n",
      "100%|███████████████████████████████████████████| 25/25 [00:03<00:00,  7.32it/s]\n",
      "/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/normalization/batch_normalization.py:67: UserWarning: A batch with no more than one sample has been given to F.batch_normalization. F.batch_normalization will always output a zero tensor for such batches. This could be caused by incorrect configuration in your code (such as running evaluation while chainer.config.train=True), but could also happen in the last batch of training if non-repeating iterator is used.\n",
      "  UserWarning)\n",
      "predictor/loss\n",
      "Exception in main training loop: \n",
      "Invalid operation is performed in: Concat (Forward)\n",
      "\n",
      "Expect: in_types[0].shape[2] == in_types[1].shape[2]\n",
      "Actual: 6 != 7\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 319, in run\n",
      "    entry.extension(self)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 157, in __call__\n",
      "    result = self.evaluate()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 211, in evaluate\n",
      "    eval_func(**in_arrays)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/updater/sr_updater.py\", line 61, in forward\n",
      "    output = self.predictor(input)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 101, in __call__\n",
      "    return self.decoder(self.encoder(x))\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 85, in __call__\n",
      "    h = F.concat([h, hs[-i - 1]])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 105, in concat\n",
      "    y, = Concat(axis).apply(xs)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 243, in apply\n",
      "    self._check_data_type_forward(in_data)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 328, in _check_data_type_forward\n",
      "    self.check_type_forward(in_type)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 41, in check_type_forward\n",
      "    type_check.expect(in_types[0].shape[d] == in_types[i].shape[d])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 524, in expect\n",
      "    expr.expect()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 482, in expect\n",
      "    '{0} {1} {2}'.format(left, self.inv, right))\n",
      "Will finalize trainer extensions and updater before reraising the exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"train_sr.py\", line 85, in <module>\n",
      "    trainer.run()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 330, in run\n",
      "    six.reraise(*sys.exc_info())\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/six.py\", line 693, in reraise\n",
      "    raise value\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 319, in run\n",
      "    entry.extension(self)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 157, in __call__\n",
      "    result = self.evaluate()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 211, in evaluate\n",
      "    eval_func(**in_arrays)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/updater/sr_updater.py\", line 61, in forward\n",
      "    output = self.predictor(input)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 101, in __call__\n",
      "    return self.decoder(self.encoder(x))\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 85, in __call__\n",
      "    h = F.concat([h, hs[-i - 1]])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 105, in concat\n",
      "    y, = Concat(axis).apply(xs)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 243, in apply\n",
      "    self._check_data_type_forward(in_data)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 328, in _check_data_type_forward\n",
      "    self.check_type_forward(in_type)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 41, in check_type_forward\n",
      "    type_check.expect(in_types[0].shape[d] == in_types[i].shape[d])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 524, in expect\n",
      "    expr.expect()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 482, in expect\n",
      "    '{0} {1} {2}'.format(left, self.inv, right))\n",
      "chainer.utils.type_check.InvalidType: \n",
      "Invalid operation is performed in: Concat (Forward)\n",
      "\n",
      "Expect: in_types[0].shape[2] == in_types[1].shape[2]\n",
      "Actual: 6 != 7\n",
      "now limit:  0.7\n",
      "rm all npy\n",
      "['__class__',\n",
      " '__contains__',\n",
      " '__delattr__',\n",
      " '__dict__',\n",
      " '__dir__',\n",
      " '__doc__',\n",
      " '__eq__',\n",
      " '__format__',\n",
      " '__ge__',\n",
      " '__getattribute__',\n",
      " '__gt__',\n",
      " '__hash__',\n",
      " '__init__',\n",
      " '__init_subclass__',\n",
      " '__le__',\n",
      " '__lt__',\n",
      " '__module__',\n",
      " '__ne__',\n",
      " '__new__',\n",
      " '__reduce__',\n",
      " '__reduce_ex__',\n",
      " '__repr__',\n",
      " '__setattr__',\n",
      " '__sizeof__',\n",
      " '__str__',\n",
      " '__subclasshook__',\n",
      " '__weakref__',\n",
      " '_get_args',\n",
      " '_get_kwargs',\n",
      " 'alpha',\n",
      " 'enable_overwrite',\n",
      " 'f0_estimating_method',\n",
      " 'frame_period',\n",
      " 'input_directory',\n",
      " 'order',\n",
      " 'output_directory',\n",
      " 'pad_second',\n",
      " 'sample_rate',\n",
      " 'top_db']\n",
      "100%|███████████████████████████████████████████| 25/25 [00:03<00:00,  7.38it/s]\n",
      "/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/normalization/batch_normalization.py:67: UserWarning: A batch with no more than one sample has been given to F.batch_normalization. F.batch_normalization will always output a zero tensor for such batches. This could be caused by incorrect configuration in your code (such as running evaluation while chainer.config.train=True), but could also happen in the last batch of training if non-repeating iterator is used.\n",
      "  UserWarning)\n",
      "predictor/loss\n",
      "Exception in main training loop: \n",
      "Invalid operation is performed in: Concat (Forward)\n",
      "\n",
      "Expect: in_types[0].shape[2] == in_types[1].shape[2]\n",
      "Actual: 6 != 7\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 319, in run\n",
      "    entry.extension(self)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 157, in __call__\n",
      "    result = self.evaluate()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 211, in evaluate\n",
      "    eval_func(**in_arrays)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/updater/sr_updater.py\", line 61, in forward\n",
      "    output = self.predictor(input)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 101, in __call__\n",
      "    return self.decoder(self.encoder(x))\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 85, in __call__\n",
      "    h = F.concat([h, hs[-i - 1]])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 105, in concat\n",
      "    y, = Concat(axis).apply(xs)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 243, in apply\n",
      "    self._check_data_type_forward(in_data)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 328, in _check_data_type_forward\n",
      "    self.check_type_forward(in_type)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 41, in check_type_forward\n",
      "    type_check.expect(in_types[0].shape[d] == in_types[i].shape[d])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 524, in expect\n",
      "    expr.expect()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 482, in expect\n",
      "    '{0} {1} {2}'.format(left, self.inv, right))\n",
      "Will finalize trainer extensions and updater before reraising the exception.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"train_sr.py\", line 85, in <module>\n",
      "    trainer.run()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 330, in run\n",
      "    six.reraise(*sys.exc_info())\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/six.py\", line 693, in reraise\n",
      "    raise value\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 319, in run\n",
      "    entry.extension(self)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 157, in __call__\n",
      "    result = self.evaluate()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 211, in evaluate\n",
      "    eval_func(**in_arrays)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/updater/sr_updater.py\", line 61, in forward\n",
      "    output = self.predictor(input)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 101, in __call__\n",
      "    return self.decoder(self.encoder(x))\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 85, in __call__\n",
      "    h = F.concat([h, hs[-i - 1]])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 105, in concat\n",
      "    y, = Concat(axis).apply(xs)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 243, in apply\n",
      "    self._check_data_type_forward(in_data)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 328, in _check_data_type_forward\n",
      "    self.check_type_forward(in_type)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 41, in check_type_forward\n",
      "    type_check.expect(in_types[0].shape[d] == in_types[i].shape[d])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 524, in expect\n",
      "    expr.expect()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 482, in expect\n",
      "    '{0} {1} {2}'.format(left, self.inv, right))\n",
      "chainer.utils.type_check.InvalidType: \n",
      "Invalid operation is performed in: Concat (Forward)\n",
      "\n",
      "Expect: in_types[0].shape[2] == in_types[1].shape[2]\n",
      "Actual: 6 != 7\n",
      "now limit:  0.7999999999999999\n",
      "rm all npy\n",
      "['__class__',\n",
      " '__contains__',\n",
      " '__delattr__',\n",
      " '__dict__',\n",
      " '__dir__',\n",
      " '__doc__',\n",
      " '__eq__',\n",
      " '__format__',\n",
      " '__ge__',\n",
      " '__getattribute__',\n",
      " '__gt__',\n",
      " '__hash__',\n",
      " '__init__',\n",
      " '__init_subclass__',\n",
      " '__le__',\n",
      " '__lt__',\n",
      " '__module__',\n",
      " '__ne__',\n",
      " '__new__',\n",
      " '__reduce__',\n",
      " '__reduce_ex__',\n",
      " '__repr__',\n",
      " '__setattr__',\n",
      " '__sizeof__',\n",
      " '__str__',\n",
      " '__subclasshook__',\n",
      " '__weakref__',\n",
      " '_get_args',\n",
      " '_get_kwargs',\n",
      " 'alpha',\n",
      " 'enable_overwrite',\n",
      " 'f0_estimating_method',\n",
      " 'frame_period',\n",
      " 'input_directory',\n",
      " 'order',\n",
      " 'output_directory',\n",
      " 'pad_second',\n",
      " 'sample_rate',\n",
      " 'top_db']\n",
      "100%|███████████████████████████████████████████| 25/25 [00:03<00:00,  7.43it/s]\n",
      "/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/normalization/batch_normalization.py:67: UserWarning: A batch with no more than one sample has been given to F.batch_normalization. F.batch_normalization will always output a zero tensor for such batches. This could be caused by incorrect configuration in your code (such as running evaluation while chainer.config.train=True), but could also happen in the last batch of training if non-repeating iterator is used.\n",
      "  UserWarning)\n",
      "predictor/loss\n",
      "Exception in main training loop: \n",
      "Invalid operation is performed in: Concat (Forward)\n",
      "\n",
      "Expect: in_types[0].shape[2] == in_types[1].shape[2]\n",
      "Actual: 6 != 7\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 319, in run\n",
      "    entry.extension(self)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 157, in __call__\n",
      "    result = self.evaluate()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 211, in evaluate\n",
      "    eval_func(**in_arrays)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/updater/sr_updater.py\", line 61, in forward\n",
      "    output = self.predictor(input)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 101, in __call__\n",
      "    return self.decoder(self.encoder(x))\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 85, in __call__\n",
      "    h = F.concat([h, hs[-i - 1]])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 105, in concat\n",
      "    y, = Concat(axis).apply(xs)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 243, in apply\n",
      "    self._check_data_type_forward(in_data)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 328, in _check_data_type_forward\n",
      "    self.check_type_forward(in_type)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 41, in check_type_forward\n",
      "    type_check.expect(in_types[0].shape[d] == in_types[i].shape[d])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 524, in expect\n",
      "    expr.expect()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 482, in expect\n",
      "    '{0} {1} {2}'.format(left, self.inv, right))\n",
      "Will finalize trainer extensions and updater before reraising the exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"train_sr.py\", line 85, in <module>\n",
      "    trainer.run()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 330, in run\n",
      "    six.reraise(*sys.exc_info())\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/six.py\", line 693, in reraise\n",
      "    raise value\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 319, in run\n",
      "    entry.extension(self)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 157, in __call__\n",
      "    result = self.evaluate()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 211, in evaluate\n",
      "    eval_func(**in_arrays)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/updater/sr_updater.py\", line 61, in forward\n",
      "    output = self.predictor(input)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 101, in __call__\n",
      "    return self.decoder(self.encoder(x))\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 85, in __call__\n",
      "    h = F.concat([h, hs[-i - 1]])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 105, in concat\n",
      "    y, = Concat(axis).apply(xs)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 243, in apply\n",
      "    self._check_data_type_forward(in_data)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 328, in _check_data_type_forward\n",
      "    self.check_type_forward(in_type)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 41, in check_type_forward\n",
      "    type_check.expect(in_types[0].shape[d] == in_types[i].shape[d])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 524, in expect\n",
      "    expr.expect()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 482, in expect\n",
      "    '{0} {1} {2}'.format(left, self.inv, right))\n",
      "chainer.utils.type_check.InvalidType: \n",
      "Invalid operation is performed in: Concat (Forward)\n",
      "\n",
      "Expect: in_types[0].shape[2] == in_types[1].shape[2]\n",
      "Actual: 6 != 7\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "now limit:  0.8999999999999999\n",
      "rm all npy\n",
      "rm file v_0011.wav\n",
      "rm file v_0029.wav\n",
      "['__class__',\n",
      " '__contains__',\n",
      " '__delattr__',\n",
      " '__dict__',\n",
      " '__dir__',\n",
      " '__doc__',\n",
      " '__eq__',\n",
      " '__format__',\n",
      " '__ge__',\n",
      " '__getattribute__',\n",
      " '__gt__',\n",
      " '__hash__',\n",
      " '__init__',\n",
      " '__init_subclass__',\n",
      " '__le__',\n",
      " '__lt__',\n",
      " '__module__',\n",
      " '__ne__',\n",
      " '__new__',\n",
      " '__reduce__',\n",
      " '__reduce_ex__',\n",
      " '__repr__',\n",
      " '__setattr__',\n",
      " '__sizeof__',\n",
      " '__str__',\n",
      " '__subclasshook__',\n",
      " '__weakref__',\n",
      " '_get_args',\n",
      " '_get_kwargs',\n",
      " 'alpha',\n",
      " 'enable_overwrite',\n",
      " 'f0_estimating_method',\n",
      " 'frame_period',\n",
      " 'input_directory',\n",
      " 'order',\n",
      " 'output_directory',\n",
      " 'pad_second',\n",
      " 'sample_rate',\n",
      " 'top_db']\n",
      "100%|███████████████████████████████████████████| 23/23 [00:03<00:00,  7.11it/s]\n",
      "/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/normalization/batch_normalization.py:67: UserWarning: A batch with no more than one sample has been given to F.batch_normalization. F.batch_normalization will always output a zero tensor for such batches. This could be caused by incorrect configuration in your code (such as running evaluation while chainer.config.train=True), but could also happen in the last batch of training if non-repeating iterator is used.\n",
      "  UserWarning)\n",
      "predictor/loss\n",
      "Exception in main training loop: \n",
      "Invalid operation is performed in: Concat (Forward)\n",
      "\n",
      "Expect: in_types[0].shape[2] == in_types[1].shape[2]\n",
      "Actual: 2 != 3\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 319, in run\n",
      "    entry.extension(self)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 157, in __call__\n",
      "    result = self.evaluate()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 211, in evaluate\n",
      "    eval_func(**in_arrays)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/updater/sr_updater.py\", line 61, in forward\n",
      "    output = self.predictor(input)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 101, in __call__\n",
      "    return self.decoder(self.encoder(x))\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 85, in __call__\n",
      "    h = F.concat([h, hs[-i - 1]])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 105, in concat\n",
      "    y, = Concat(axis).apply(xs)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 243, in apply\n",
      "    self._check_data_type_forward(in_data)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 328, in _check_data_type_forward\n",
      "    self.check_type_forward(in_type)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 41, in check_type_forward\n",
      "    type_check.expect(in_types[0].shape[d] == in_types[i].shape[d])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 524, in expect\n",
      "    expr.expect()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 482, in expect\n",
      "    '{0} {1} {2}'.format(left, self.inv, right))\n",
      "Will finalize trainer extensions and updater before reraising the exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"train_sr.py\", line 85, in <module>\n",
      "    trainer.run()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 330, in run\n",
      "    six.reraise(*sys.exc_info())\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/six.py\", line 693, in reraise\n",
      "    raise value\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/trainer.py\", line 319, in run\n",
      "    entry.extension(self)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 157, in __call__\n",
      "    result = self.evaluate()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/training/extensions/evaluator.py\", line 211, in evaluate\n",
      "    eval_func(**in_arrays)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/updater/sr_updater.py\", line 61, in forward\n",
      "    output = self.predictor(input)\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 101, in __call__\n",
      "    return self.decoder(self.encoder(x))\n",
      "  File \"/home/aideep2018a/become-yukarin/become_yukarin/model/sr_model.py\", line 85, in __call__\n",
      "    h = F.concat([h, hs[-i - 1]])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 105, in concat\n",
      "    y, = Concat(axis).apply(xs)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 243, in apply\n",
      "    self._check_data_type_forward(in_data)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/function_node.py\", line 328, in _check_data_type_forward\n",
      "    self.check_type_forward(in_type)\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/array/concat.py\", line 41, in check_type_forward\n",
      "    type_check.expect(in_types[0].shape[d] == in_types[i].shape[d])\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 524, in expect\n",
      "    expr.expect()\n",
      "  File \"/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/utils/type_check.py\", line 482, in expect\n",
      "    '{0} {1} {2}'.format(left, self.inv, right))\n",
      "chainer.utils.type_check.InvalidType: \n",
      "Invalid operation is performed in: Concat (Forward)\n",
      "\n",
      "Expect: in_types[0].shape[2] == in_types[1].shape[2]\n",
      "Actual: 2 != 3\n",
      "now limit:  0.9999999999999999\n",
      "rm all npy\n",
      "rm file v_0030.wav\n",
      "['__class__',\n",
      " '__contains__',\n",
      " '__delattr__',\n",
      " '__dict__',\n",
      " '__dir__',\n",
      " '__doc__',\n",
      " '__eq__',\n",
      " '__format__',\n",
      " '__ge__',\n",
      " '__getattribute__',\n",
      " '__gt__',\n",
      " '__hash__',\n",
      " '__init__',\n",
      " '__init_subclass__',\n",
      " '__le__',\n",
      " '__lt__',\n",
      " '__module__',\n",
      " '__ne__',\n",
      " '__new__',\n",
      " '__reduce__',\n",
      " '__reduce_ex__',\n",
      " '__repr__',\n",
      " '__setattr__',\n",
      " '__sizeof__',\n",
      " '__str__',\n",
      " '__subclasshook__',\n",
      " '__weakref__',\n",
      " '_get_args',\n",
      " '_get_kwargs',\n",
      " 'alpha',\n",
      " 'enable_overwrite',\n",
      " 'f0_estimating_method',\n",
      " 'frame_period',\n",
      " 'input_directory',\n",
      " 'order',\n",
      " 'output_directory',\n",
      " 'pad_second',\n",
      " 'sample_rate',\n",
      " 'top_db']\n",
      "100%|███████████████████████████████████████████| 22/22 [00:03<00:00,  6.91it/s]\n",
      "/home/aideep2018a/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/chainer/functions/normalization/batch_normalization.py:67: UserWarning: A batch with no more than one sample has been given to F.batch_normalization. F.batch_normalization will always output a zero tensor for such batches. This could be caused by incorrect configuration in your code (such as running evaluation while chainer.config.train=True), but could also happen in the last batch of training if non-repeating iterator is used.\n",
      "  UserWarning)\n",
      "predictor/loss\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import wave\n",
    "wav_limit_length = 0\n",
    "\n",
    "while True:\n",
    "    print('now limit: ', wav_limit_length)\n",
    "    # npy files delete\n",
    "    !rm dat/out_2nd_yukari_many_npy/*.npy\n",
    "    print('rm all npy')\n",
    "\n",
    "    # check wav_length\n",
    "    path = \"./dat/in_2nd_yukari_many_wav/\"\n",
    "    files = os.listdir(path)\n",
    "\n",
    "    for file in sorted(files):\n",
    "        if file != \".keep\":\n",
    "            wavfile = wave.open(path + file, \"r\")\n",
    "            wav_length = float(wavfile.getnframes()) / wavfile.getframerate()\n",
    "            if wav_length < wav_limit_length:\n",
    "                os.remove(path + file)\n",
    "                print('rm file', file)\n",
    "\n",
    "    try:\n",
    "        !python scripts/extract_spectrogram_pair.py -i dat/in_2nd_yukari_many_wav -o dat/out_2nd_yukari_many_npy\n",
    "        !python train_sr.py dat/config_sr.json dat/model/yukari_2nd\n",
    "        wav_limit_length += 0.1\n",
    "    except:\n",
    "        pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "rm file v_0001.wav\n",
      "rm file v_0002.wav\n",
      "rm file v_0003.wav\n",
      "rm file v_0004.wav\n",
      "rm file v_0005.wav\n",
      "rm file v_0006.wav\n",
      "rm file v_0007.wav\n",
      "rm file v_0008.wav\n",
      "rm file v_0009.wav\n",
      "rm file v_0010.wav\n",
      "rm file v_0011.wav\n",
      "rm file v_0012.wav\n",
      "rm file v_0013.wav\n",
      "rm file v_0014.wav\n",
      "rm file v_0016.wav\n",
      "rm file v_0021.wav\n",
      "rm file v_0022.wav\n",
      "rm file v_0023.wav\n",
      "rm file v_0024.wav\n",
      "rm file v_0025.wav\n",
      "rm file v_0026.wav\n",
      "rm file v_0027.wav\n",
      "rm file v_0028.wav\n",
      "rm file v_0029.wav\n",
      "rm file v_0030.wav\n",
      "rm file v_0031.wav\n",
      "rm file v_0032.wav\n",
      "rm file v_0033.wav\n",
      "rm file v_0034.wav\n",
      "rm file v_0037.wav\n",
      "rm file v_0038.wav\n",
      "rm file v_0039.wav\n",
      "rm file v_0040.wav\n",
      "rm file v_0042.wav\n",
      "rm file v_0043.wav\n",
      "rm file v_0044.wav\n",
      "rm file v_0045.wav\n",
      "rm file v_0046.wav\n",
      "rm file v_0047.wav\n",
      "rm file v_0049.wav\n",
      "rm file v_0050.wav\n",
      "rm file v_0052.wav\n",
      "rm file v_0053.wav\n",
      "rm file v_0054.wav\n",
      "rm file v_0055.wav\n",
      "rm file v_0056.wav\n",
      "rm file v_0062.wav\n",
      "rm file v_0063.wav\n",
      "rm file v_0064.wav\n",
      "rm file v_0065.wav\n",
      "rm file v_0067.wav\n",
      "rm file v_0068.wav\n",
      "rm file v_0072.wav\n",
      "rm file v_0073.wav\n",
      "rm file v_0074.wav\n",
      "rm file v_0075.wav\n",
      "rm file v_0076.wav\n",
      "rm file v_0077.wav\n",
      "rm file v_0078.wav\n",
      "rm file v_0079.wav\n",
      "rm file v_0080.wav\n",
      "rm file v_0081.wav\n",
      "rm file v_0082.wav\n",
      "rm file v_0083.wav\n",
      "rm file v_0084.wav\n",
      "rm file v_0085.wav\n",
      "rm file v_0086.wav\n",
      "rm file v_0088.wav\n",
      "rm file v_0090.wav\n",
      "rm file v_0091.wav\n",
      "rm file v_0092.wav\n",
      "rm file v_0093.wav\n",
      "rm file v_0094.wav\n",
      "rm file v_0097.wav\n",
      "rm file v_0099.wav\n",
      "rm file v_0100.wav\n",
      "rm file v_0103.wav\n",
      "rm file v_0104.wav\n",
      "rm file v_0105.wav\n",
      "rm file v_0106.wav\n",
      "rm file v_0107.wav\n",
      "rm file v_0108.wav\n",
      "rm file v_0110.wav\n",
      "rm file v_0111.wav\n",
      "rm file v_0112.wav\n",
      "rm file v_0113.wav\n",
      "rm file v_0114.wav\n",
      "rm file v_0116.wav\n",
      "rm file v_0117.wav\n",
      "rm file v_0118.wav\n",
      "rm file v_0119.wav\n",
      "rm file v_0120.wav\n",
      "rm file v_0121.wav\n",
      "rm file v_0122.wav\n",
      "rm file v_0123.wav\n",
      "rm file v_0124.wav\n",
      "rm file v_0125.wav\n",
      "rm file v_0126.wav\n",
      "rm file v_0127.wav\n",
      "rm file v_0128.wav\n",
      "rm file v_0129.wav\n",
      "rm file v_0130.wav\n",
      "rm file v_0132.wav\n",
      "rm file v_0133.wav\n",
      "rm file v_0134.wav\n",
      "rm file v_0135.wav\n",
      "rm file v_0136.wav\n",
      "rm file v_0137.wav\n",
      "rm file v_0138.wav\n",
      "rm file v_0139.wav\n",
      "rm file v_0140.wav\n",
      "rm file v_0141.wav\n",
      "rm file v_0143.wav\n",
      "rm file v_0144.wav\n",
      "rm file v_0146.wav\n",
      "rm file v_0147.wav\n",
      "rm file v_0148.wav\n",
      "rm file v_0149.wav\n",
      "rm file v_0150.wav\n",
      "rm file v_0151.wav\n",
      "rm file v_0153.wav\n",
      "rm file v_0155.wav\n",
      "rm file v_0156.wav\n",
      "rm file v_0157.wav\n",
      "rm file v_0158.wav\n",
      "rm file v_0159.wav\n",
      "rm file v_0160.wav\n",
      "rm file v_0161.wav\n",
      "rm file v_0162.wav\n",
      "rm file v_0163.wav\n",
      "rm file v_0164.wav\n",
      "rm file v_0165.wav\n",
      "rm file v_0166.wav\n",
      "rm file v_0167.wav\n",
      "rm file v_0168.wav\n",
      "rm file v_0169.wav\n",
      "rm file v_0170.wav\n",
      "rm file v_0171.wav\n",
      "rm file v_0172.wav\n",
      "rm file v_0173.wav\n",
      "rm file v_0174.wav\n",
      "rm file v_0175.wav\n",
      "rm file v_0176.wav\n",
      "rm file v_0177.wav\n",
      "rm file v_0178.wav\n",
      "rm file v_0179.wav\n",
      "rm file v_0180.wav\n",
      "rm file v_0181.wav\n",
      "rm file v_0182.wav\n",
      "rm file v_0183.wav\n",
      "rm file v_0184.wav\n",
      "rm file v_0185.wav\n",
      "rm file v_0186.wav\n",
      "rm file v_0187.wav\n",
      "rm file v_0188.wav\n",
      "rm file v_0189.wav\n",
      "rm file v_0190.wav\n",
      "rm file v_0191.wav\n",
      "rm file v_0192.wav\n",
      "rm file v_0193.wav\n",
      "rm file v_0194.wav\n",
      "rm file v_0195.wav\n",
      "rm file v_0196.wav\n",
      "rm file v_0197.wav\n",
      "rm file v_0198.wav\n",
      "rm file v_0199.wav\n",
      "rm file v_0200.wav\n",
      "rm file v_0201.wav\n",
      "rm file v_0202.wav\n",
      "rm file v_0203.wav\n",
      "rm file v_0204.wav\n",
      "rm file v_0205.wav\n",
      "rm file v_0206.wav\n",
      "rm file v_0207.wav\n",
      "rm file v_0208.wav\n",
      "rm file v_0209.wav\n",
      "rm file v_0210.wav\n",
      "rm file v_0211.wav\n",
      "rm file v_0212.wav\n",
      "rm file v_0213.wav\n",
      "rm file v_0214.wav\n",
      "rm file v_0215.wav\n",
      "rm file v_0216.wav\n",
      "rm file v_0217.wav\n",
      "rm file v_0218.wav\n",
      "rm file v_0219.wav\n",
      "rm file v_0220.wav\n",
      "rm file v_0221.wav\n",
      "rm file v_0222.wav\n",
      "rm file v_0223.wav\n",
      "rm file v_0224.wav\n",
      "rm file v_0225.wav\n",
      "rm file v_0226.wav\n",
      "rm file v_0227.wav\n",
      "rm file v_0228.wav\n",
      "rm file v_0229.wav\n",
      "rm file v_0230.wav\n",
      "rm file v_0231.wav\n",
      "rm file v_0232.wav\n",
      "rm file v_0233.wav\n",
      "rm file v_0234.wav\n",
      "rm file v_0235.wav\n",
      "rm file v_0236.wav\n",
      "rm file v_0237.wav\n",
      "rm file v_0238.wav\n",
      "rm file v_0239.wav\n",
      "rm file v_0240.wav\n",
      "rm file v_0241.wav\n",
      "rm file v_0242.wav\n",
      "rm file v_0243.wav\n",
      "rm file v_0244.wav\n",
      "rm file v_0245.wav\n",
      "rm file v_0246.wav\n",
      "rm file v_0247.wav\n",
      "rm file v_0248.wav\n",
      "rm file v_0249.wav\n",
      "rm file v_0250.wav\n",
      "rm file v_0251.wav\n",
      "rm file v_0252.wav\n",
      "rm file v_0253.wav\n",
      "rm file v_0254.wav\n",
      "rm file v_0255.wav\n",
      "rm file v_0256.wav\n",
      "rm file v_0257.wav\n",
      "rm file v_0258.wav\n",
      "rm file v_0259.wav\n",
      "rm file v_0260.wav\n",
      "rm file v_0261.wav\n",
      "rm file v_0262.wav\n",
      "rm file v_0263.wav\n",
      "rm file v_0264.wav\n",
      "rm file v_0265.wav\n",
      "rm file v_0266.wav\n",
      "rm file v_0267.wav\n",
      "rm file v_0268.wav\n",
      "rm file v_0269.wav\n",
      "rm file v_0270.wav\n",
      "rm file v_0271.wav\n",
      "rm file v_0272.wav\n",
      "rm file v_0273.wav\n",
      "rm file v_0274.wav\n",
      "rm file v_0275.wav\n",
      "rm file v_0276.wav\n",
      "rm file v_0277.wav\n",
      "rm file v_0278.wav\n",
      "rm file v_0279.wav\n",
      "rm file v_0280.wav\n",
      "rm file v_0281.wav\n",
      "rm file v_0282.wav\n",
      "rm file v_0283.wav\n",
      "rm file v_0284.wav\n",
      "rm file v_0285.wav\n",
      "rm file v_0286.wav\n",
      "rm file v_0287.wav\n",
      "rm file v_0288.wav\n",
      "rm file v_0289.wav\n",
      "rm file v_0290.wav\n",
      "rm file v_0291.wav\n",
      "rm file v_0292.wav\n",
      "rm file v_0293.wav\n",
      "rm file v_0294.wav\n",
      "rm file v_0295.wav\n",
      "rm file v_0296.wav\n",
      "rm file v_0297.wav\n",
      "rm file v_0298.wav\n",
      "rm file v_0299.wav\n",
      "rm file v_0300.wav\n",
      "rm file v_0301.wav\n",
      "rm file v_0302.wav\n",
      "rm file v_0303.wav\n",
      "rm file v_0304.wav\n",
      "rm file v_0305.wav\n",
      "rm file v_0306.wav\n",
      "rm file v_0307.wav\n",
      "rm file v_0308.wav\n",
      "rm file v_0309.wav\n",
      "rm file v_0310.wav\n",
      "rm file v_0311.wav\n",
      "rm file v_0312.wav\n",
      "rm file v_0313.wav\n",
      "rm file v_0314.wav\n",
      "rm file v_0315.wav\n",
      "rm file v_0316.wav\n",
      "rm file v_0317.wav\n",
      "rm file v_0318.wav\n",
      "rm file v_0319.wav\n",
      "rm file v_0320.wav\n",
      "rm file v_0321.wav\n",
      "rm file v_0322.wav\n",
      "rm file v_0323.wav\n",
      "rm file v_0324.wav\n",
      "rm file v_0325.wav\n",
      "rm file v_0326.wav\n",
      "rm file v_0327.wav\n",
      "rm file v_0328.wav\n",
      "rm file v_0329.wav\n",
      "rm file v_0330.wav\n",
      "rm file v_0331.wav\n",
      "rm file v_0332.wav\n",
      "rm file v_0333.wav\n",
      "rm file v_0334.wav\n",
      "rm file v_0335.wav\n",
      "rm file v_0336.wav\n",
      "rm file v_0337.wav\n",
      "rm file v_0338.wav\n",
      "rm file v_0339.wav\n",
      "rm file v_0340.wav\n",
      "rm file v_0341.wav\n",
      "rm file v_0342.wav\n",
      "rm file v_0343.wav\n",
      "rm file v_0344.wav\n",
      "rm file v_0345.wav\n",
      "rm file v_0346.wav\n",
      "rm file v_0347.wav\n",
      "rm file v_0348.wav\n",
      "rm file v_0349.wav\n",
      "rm file v_0350.wav\n",
      "rm file v_0351.wav\n",
      "rm file v_0352.wav\n",
      "rm file v_0353.wav\n",
      "rm file v_0354.wav\n",
      "rm file v_0355.wav\n",
      "rm file v_0356.wav\n",
      "rm file v_0357.wav\n",
      "rm file v_0358.wav\n",
      "rm file v_0359.wav\n",
      "rm file v_0360.wav\n",
      "rm file v_0361.wav\n",
      "rm file v_0362.wav\n",
      "rm file v_0363.wav\n",
      "rm file v_0364.wav\n",
      "rm file v_0365.wav\n",
      "rm file v_0366.wav\n",
      "rm file v_0367.wav\n",
      "rm file v_0368.wav\n",
      "rm file v_0369.wav\n",
      "rm file v_0370.wav\n",
      "rm file v_0371.wav\n",
      "rm file v_0372.wav\n",
      "rm file v_0373.wav\n",
      "rm file v_0374.wav\n",
      "rm file v_0375.wav\n",
      "rm file v_0376.wav\n",
      "rm file v_0377.wav\n",
      "rm file v_0378.wav\n",
      "rm file v_0379.wav\n",
      "rm file v_0380.wav\n",
      "rm file v_0381.wav\n",
      "rm file v_0382.wav\n",
      "rm file v_0383.wav\n",
      "rm file v_0384.wav\n",
      "rm file v_0385.wav\n",
      "rm file v_0386.wav\n",
      "rm file v_0387.wav\n",
      "rm file v_0388.wav\n",
      "rm file v_0389.wav\n",
      "rm file v_0390.wav\n",
      "rm file v_0391.wav\n",
      "rm file v_0392.wav\n",
      "rm file v_0393.wav\n",
      "rm file v_0394.wav\n",
      "rm file v_0395.wav\n",
      "rm file v_0396.wav\n",
      "rm file v_0397.wav\n",
      "rm file v_0398.wav\n",
      "rm file v_0399.wav\n",
      "rm file v_0400.wav\n",
      "rm file v_0401.wav\n",
      "rm file v_0402.wav\n",
      "rm file v_0403.wav\n",
      "rm file v_0404.wav\n",
      "rm file v_0405.wav\n",
      "rm file v_0406.wav\n",
      "rm file v_0407.wav\n",
      "rm file v_0408.wav\n",
      "rm file v_0409.wav\n",
      "rm file v_0410.wav\n",
      "rm file v_0411.wav\n",
      "rm file v_0412.wav\n",
      "rm file v_0413.wav\n",
      "rm file v_0414.wav\n",
      "rm file v_0415.wav\n",
      "rm file v_0416.wav\n",
      "rm file v_0417.wav\n",
      "rm file v_0418.wav\n",
      "rm file v_0419.wav\n",
      "rm file v_0420.wav\n",
      "rm file v_0421.wav\n",
      "rm file v_0422.wav\n",
      "rm file v_0423.wav\n",
      "rm file v_0424.wav\n",
      "rm file v_0425.wav\n",
      "rm file v_0426.wav\n",
      "rm file v_0427.wav\n",
      "rm file v_0428.wav\n",
      "rm file v_0429.wav\n",
      "rm file v_0430.wav\n",
      "rm file v_0431.wav\n",
      "rm file v_0432.wav\n",
      "rm file v_0433.wav\n",
      "rm file v_0434.wav\n",
      "rm file v_0435.wav\n",
      "rm file v_0436.wav\n",
      "rm file v_0437.wav\n",
      "rm file v_0438.wav\n",
      "rm file v_0439.wav\n",
      "rm file v_0440.wav\n",
      "rm file v_0441.wav\n",
      "rm file v_0442.wav\n",
      "rm file v_0443.wav\n",
      "rm file v_0444.wav\n",
      "rm file v_0445.wav\n",
      "rm file v_0446.wav\n",
      "rm file v_0447.wav\n",
      "rm file v_0448.wav\n",
      "rm file v_0449.wav\n",
      "rm file v_0450.wav\n",
      "rm file v_0451.wav\n",
      "rm file v_0452.wav\n",
      "rm file v_0453.wav\n",
      "rm file v_0454.wav\n",
      "rm file v_0455.wav\n",
      "rm file v_0456.wav\n",
      "rm file v_0457.wav\n",
      "rm file v_0458.wav\n",
      "rm file v_0459.wav\n",
      "rm file v_0460.wav\n",
      "rm file v_0461.wav\n",
      "rm file v_0462.wav\n",
      "rm file v_0463.wav\n",
      "rm file v_0464.wav\n",
      "rm file v_0465.wav\n",
      "rm file v_0466.wav\n",
      "rm file v_0467.wav\n",
      "rm file v_0468.wav\n",
      "rm file v_0469.wav\n",
      "rm file v_0470.wav\n",
      "rm file v_0471.wav\n",
      "rm file v_0472.wav\n",
      "rm file v_0473.wav\n",
      "rm file v_0474.wav\n",
      "rm file v_0475.wav\n",
      "rm file v_0476.wav\n",
      "rm file v_0477.wav\n",
      "rm file v_0478.wav\n",
      "rm file v_0479.wav\n",
      "rm file v_0480.wav\n",
      "rm file v_0481.wav\n",
      "rm file v_0482.wav\n",
      "rm file v_0483.wav\n",
      "rm file v_0484.wav\n",
      "rm file v_0485.wav\n",
      "rm file v_0486.wav\n",
      "rm file v_0487.wav\n",
      "rm file v_0488.wav\n",
      "rm file v_0489.wav\n",
      "rm file v_0491.wav\n",
      "rm file v_0492.wav\n",
      "rm file v_0493.wav\n",
      "rm file v_0494.wav\n",
      "rm file v_0495.wav\n",
      "rm file v_0496.wav\n",
      "rm file v_0497.wav\n",
      "rm file v_0498.wav\n",
      "rm file v_0499.wav\n",
      "rm file v_0500.wav\n",
      "rm file v_0501.wav\n",
      "rm file v_0502.wav\n",
      "rm file v_0503.wav\n",
      "rm file v_0504.wav\n",
      "rm file v_0505.wav\n",
      "rm file v_0506.wav\n",
      "rm file v_0507.wav\n",
      "rm file v_0508.wav\n",
      "rm file v_0509.wav\n",
      "rm file v_0510.wav\n",
      "rm file v_0511.wav\n",
      "rm file v_0512.wav\n",
      "rm file v_0513.wav\n",
      "rm file v_0514.wav\n",
      "rm file v_0515.wav\n",
      "rm file v_0516.wav\n",
      "rm file v_0517.wav\n",
      "rm file v_0518.wav\n",
      "rm file v_0519.wav\n",
      "rm file v_0520.wav\n",
      "rm file v_0521.wav\n",
      "rm file v_0522.wav\n",
      "rm file v_0523.wav\n",
      "rm file v_0524.wav\n",
      "rm file v_0525.wav\n",
      "rm file v_0526.wav\n",
      "rm file v_0527.wav\n",
      "rm file v_0528.wav\n",
      "rm file v_0529.wav\n",
      "rm file v_0530.wav\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import wave\n",
    "# check wav_length\n",
    "path = \"./dat/in_2nd_yukari_many_wav/\"\n",
    "files = os.listdir(path)\n",
    "\n",
    "for file in sorted(files):\n",
    "    if file != \".keep\":\n",
    "        wavfile = wave.open(path + file, \"r\")\n",
    "        wav_length = float(wavfile.getnframes()) / wavfile.getframerate()\n",
    "        os.remove(path + file)\n",
    "        print('rm file', file)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
